### ISSUE TITLE
Añadir README

### ISSUE THREAD

**Issue by edzzn** [javascriptecuador/web#1]
Cada proyecto open source tiene un archivo README.md en el que se especifica informacion sobre el repositorio, comunidad, etc.  El README es lo primero que veran quienes visiten el repositorio.

Para esta tarea es necesario conocer [Markdown](https://guides.github.com/features/mastering-markdown/) y debes crear un archivo `README.md` escrito en formato Markdown que muestre lo siguiente:
  
- Presentación del sitio 
- Una pequeña descripción de la comunidad `Javascript Ecuador`
- Pasos de como utilizar el proyecto hacerlo funcionar en tu computadora, ya sea windows, linux o mac.
 
Se intenta tener algo simple, elegante y facil de leer un ejemplo lo podrias ver [aqui](https://github.com/sendgrid/docs) o muchas mas en este repositorio [awesome-readme](https://github.com/matiassingers/awesome-readme)

> El sitio se desarrolla en [Gatsby](https://www.gatsbyjs.com/tutorial/) y usando [Tailwindcss](https://tailwindcss.com/) para los estilos.

Cualquier inquietud puedes preguntar aqui en un comentario o en nuestro canal de [Telegram](https://t.me/javascriptecuador).

**Comment by Anoop01234** [comment]
Can you guide me what am I suppose to do it?

**Comment by israteneda** [comment]
We'll provide more information in the coming days

**Comment by jordanrjdev** [comment]
I am working in this readme

**Comment by israteneda** [comment]
Genial @jordanrjcode te asignaré este issue

**Comment by miguel-rios-r** [comment]
@jordanrjcode por fa, tengo un PR solo con la cabecera del ReadMe, podrías revisarlo y añadir esto al Read me completo que estás creando... te agradecería un montón!!!!
