### ISSUE TITLE
Añadir CONTRIBUTING.md

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#12]
Añadir un archivo escrito en Markdown que muestra las instrucciones detallas de como contribuir en la página de JavaScript Ecuador

**Comment by israteneda** [comment]
Añadir un archivo escrito en Markdown que muestra las instrucciones detallas de como contribuir en la página de JavaScript Ecuador

**Comment by rpalaciosg** [comment]
Agregare una propuesta base para este Issue.

**Comment by israteneda** [comment]
Genial
