### ISSUE TITLE
Implementar linter para commits

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#13]
Deseamos seguir una convencion estandar como [ConventionalCommits](https://www.conventionalcommits.org/en/v1.0.0/) al momento de escribir mensajes de commit en este repositorio; sobre todo para cuando se este trabajando localmennte en el codigo.

Para eso tenemos pensado usar un linter llamado [commitlint](https://github.com/conventional-changelog/commitlint#getting-started), el cual nos ayudara en nuestro objetivo. 

Como parte de este issue se podria automatizar las validaciones de este linter usando hooks de git mediante [husky](https://github.com/typicode/husky).

En esta tarea se debe configurar commit lint y automatizar con un git hook  en pre-commit.  Si es posible, crear una guia rapida de como instalarlo y configurarlo, sino se podria abrir un nuevo issue para la tarea de esta guia.

Cualquier inquietud comentala aqui o pregunta en el  [canal deTelegram](https://t.me/javascriptecuador)

**Comment by cesardlinx** [comment]
Yo me puedo encargar de ello!
