### ISSUE TITLE
Agregar guía sobre ConventionalCommits en CONTRIBUTING

### ISSUE THREAD

**Issue by EduardoAyora** [javascriptecuador/web#16]
Se puede agregar una guía parecida a [esta](https://www.aunitz.net/conventional-commits/#:~:text=Una%20convenci%C3%B3n%20para%20dar%20significado%20a%20los%20mensajes%20de%20los%20commits&text=El%20mes%20pasado%20dejo%20de,legibles%20para%20m%C3%A1quinas%20y%20humanos.) pero resumida

**Comment by EduardoAyora** [comment]
yo podría hacerla, si les parece que puede aportar

**Comment by israteneda** [comment]
Claro estaría genial

**Comment by EduardoAyora** [comment]
listo, ya lo hago

**Comment by israteneda** [comment]
Se resolvió en #17 por @EduardoAyora
