### ISSUE TITLE
Publicar página

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#19]
Tenemos que publicar la página con Netlify y si es posible también eliminar el anterior [repo](https://github.com/javascriptecuador/javascriptecuador.github.com) para que no haya confusión

**Comment by rpalaciosg** [comment]
Si en este caso simplemente se deberia remplazar el repo anterior con este. Para hacerlo tendrias que conectarte con la cuenta Netlify de javascript ecuador y cambiar el repositorio. 

Ademas de hacer el deploy en esta tarea se podria crear una guia de como hacer el deploy del sitio en netlify talvez creando un `how-to-deploy.md`
