### ISSUE TITLE
Crear componente Navbar

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#2]
En esta tarea debemos crear el componente Navbar y agregarlo en el Homepage del sitio

![image](https://user-images.githubusercontent.com/11642622/94996882-e4e8c900-056c-11eb-9972-2aeba55bba8a.png)

En el siguiente link esta el prototipo en figma para ver los colores y tamanios de cada item.

https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier inquietud puedes comentarla aqui o escribir en el [chat de la comuniad en telegram](https://t.me/javascriptecuador)

**Comment by cesardlinx** [comment]
Yo puedo encargarme de este issue si no hay gente trabajando ya en el

**Comment by israteneda** [comment]
@rpalaciosg me parece que estaba trabajando en este issue, aunque no sé cómo este el avance creo que ya comentara el issue a ver que nos dice

**Comment by rpalaciosg** [comment]
Hola amigos @israteneda @cesardlinx , si yo estoy trabajando en esto, aun estoy terminandolo estaba luchando con el tailwind, pero a penas este haga el PR, no me quiero dar por vencido.

**Comment by cesardlinx** [comment]
Oh jaja ok chévere! Si necesitan ayuda déjenme saber
