### ISSUE TITLE
Agregar guia para actualizar cambios del Repo principal a los fork 

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#22]
Es importante siempre hacer un `git pull`  para verificar si hay nuevos cambios en el repo.

En el archivo CONTRIBUTING.md en la guia de como contribuir, falta una guia que explique como actualizar los forks realizados al repo original.

En esta tarea es necesario escribir una pequeña guia que explique  como hacerlo.

Cualquier inquietud puedes comentarla aqui o escribir en el [chat de la comuniad en telegram](https://t.me/javascriptecuador)

**Comment by EduardoAyora** [comment]
Yo lo aprendí con esta guía, por si le sirve de algo al que vaya a resolver al Issue 
https://styde.net/actualizar-el-fork-de-un-repositorio-de-github/

Nota: No el video, sino los comandos que están abajo.

**Comment by rpalaciosg** [comment]
Genial, muchas gracias Eduardo.

**Comment by rpalaciosg** [comment]
Hola amigos como va este issue? seria bueno actualizar la guia ya que algunos ya van por su segundo PR y no tienen actualizado el fork.

**Comment by albamaister** [comment]
Hola a todos, voy a tomar este issue
