### ISSUE TITLE
La sintaxis de Markdown no se está aplicando

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#24]
Al escribir un blog y añadir la numeración no se muestra los números como debería mostrarse solo el texto

![](https://user-images.githubusercontent.com/11642622/95367160-06fa8800-089a-11eb-88a2-0566b27ab9db.png)

Este es el código en Markdown:

```
---
title: Deploy de un sitio de Gatsby en Netlify
date: "2020-10-05"
updated: "2020-10-05"
description: Como realizar el deploy de un sitio construido con Gatsby a Netlify
---

Esta es la guía base para realizar el deploy de una página construida con el framework Gatsby,
en este caso se realizará el deploy de la página de la comunidad de JavaScript Ecuador.

Una vez tenemos el sitio alojado en un repositorio de GitHub tenemos que conectarlo con la plataforma
[Netlify](https://www.netlify.com/).

1. Añadir el repostiorio desde GitHub

![](https://cdn.netlify.com/3803d207cbf97389f0d37ab7ee65580ee52c217f/a6a2f/img/blog/new_site_button.png)

2. Conectar el repositorio

Hacer clic en el botón que lleva a la pantalla donde Netlify se conecta al repositorio de GitHub. 

![](https://cdn.netlify.com/6cc161f3ced8f060296bc8aeacd7fb39e5159274/743e1/img/blog/create_link_repo.png)
```

**Comment by stsewd** [comment]
Parece que esto ya está arreglado :)

https://javascriptecuador.netlify.app/blog/gatsby-deploy/

![Screenshot_2020-10-07 About](https://user-images.githubusercontent.com/4975310/95411564-6bdece00-08ec-11eb-9fbd-aaa020ec88cf.png)

**Comment by israteneda** [comment]
Si momentáneamente 😅 le pusimos como subtítulos los numerales y no nos reconoce los espacios quisa tenemos que verlo más a  fondo que está pasando
