### ISSUE TITLE
Agregar guia para desplegar y configurar proyecto localmente

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#26]
Seria necerario que despues de hacer el fork y clonar el repositorio, agregar una guia que explique como configurar y desplegar el proyecto gatsby localmente.

Si tienes alguna duda o necesitas guia, comentalo por aqui en los comentarios o escribenos al [canal de telegram](https://t.me/javascriptecuador) de la comunidad.

**Comment by skcode7** [comment]
Me pido este issue para documentar el proceso aprovechando que voy a levantar mi ambiente.
