### ISSUE TITLE
Crear sección comunidad del Home

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#28]
![image](https://user-images.githubusercontent.com/20668624/95643430-bbe89c80-0a74-11eb-845d-50094b0c0ce8.png)

Gracias al pull #27 de @cesardlinx ya existe el slider, faltan algunos componentes para terminar la sección de comunidad de la página principal.

**Comment by rpalaciosg** [comment]
Genial, entonces podemos cerrar este issue?

**Comment by israteneda** [comment]
Todavía falta completar la sección comunidad, lo que se tiene hasta ahora es el slider pero estamos cerca 😃

**Comment by cesardlinx** [comment]
Yo puedo terminar de crear la sección si es que no hay ningún inconveniente

**Comment by israteneda** [comment]
Claro estaría genial ya tendríamos más avanzado el home
