### ISSUE TITLE
Crear un Issue Template de Features

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#30]
Para tener un standar al momento de rectar un issue solicitando nuevas caracteristicas seria bueno crear un issue-template para tener una pauta de que informacion detallar.

Dejo una guia para hacerlo -> [Configurar template Features Request](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

Si tienes alguna pregunta, comentala aqui o escribelo en el canal de [Telegram de la Comunidad](https://t.me/javascriptecuador)

**Comment by jordanrjdev** [comment]
Me encargo de este issue

**Comment by israteneda** [comment]
Genial @jordanrjcode
