### ISSUE TITLE
Crear un Issue Template para Bugs/Errores

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#31]
Para tener un standar al momento de rectar un issue reportando un **bug/error**, seria bueno crear un issue-template para tener una pauta de que informacion detallar.

Dejo una guia para hacerlo -> [Configurar template Features Request](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

Si tienes alguna pregunta, comentala aqui o escribelo en el canal de [Telegram de la Comunidad](https://t.me/javascriptecuador)

**Comment by israteneda** [comment]
Ya que estamos en estas sería bueno tener un template para el envío de los pull request como el pull que se realiza en #27

**Comment by rpalaciosg** [comment]
Claro ya esta el Issue y le envie un PR, como lo hacen en #27 mas que todo para hacer un `Closes #<issue_id>` y cerrar automaticamente los issues apenas se haga el merge. Por cierto issue #28 ya se puede cerrar?

**Comment by skcode7** [comment]
Voy a trabajar en este tema y de paso lo pruebo creando el issue para corregir la sección de eventos

**Comment by israteneda** [comment]
Genial @skcode7

**Comment by skcode7** [comment]
Tengo una duda,
Por temas de permisos no puedo crear el template en el repositorio de la comunidad, así que lo hice en el mio. Pero cuando termino y genera el commit, se hace el **PR** en el mío.

Como paso el template al repo de la comunidad?

**Comment by israteneda** [comment]
Habría que crear el template en la carpeta de [`.github`](https://github.com/javascriptecuador/web/tree/master/.github) como los demás templates, y cuando realices el pull ya lo mergeariamos y aparecería el template. 
Me parece que ya existe un temple del issue, pero deberíamos migrarlo a la forma más actual de manejar los templates como se muestra en este link: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates
PD: Te añadiré como miembro de la comunidad para que tengas más permisos.

**Comment by skcode7** [comment]
Listo!
Me costó armar el **PR** pero ya quedó 😜
