### ISSUE TITLE
Crear sección eventos del home

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#39]
Como referencia se puede tener #40 

![image](https://user-images.githubusercontent.com/20668624/95782127-d5682f00-0c94-11eb-90c2-fb3f99565e4b.png)

Se puede ver más sobre el prototipo en Figma en esta direccción https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier duda se la puede consultar por el chat de [Telegram](https://t.me/javascriptecuador)

**Comment by skcode7** [comment]
Me apunto para trabajar en este issue

**Comment by skcode7** [comment]
Tengo una duda:
En el diseño en Figma, el fondo de las tarjetas de los eventos es de color `#E5E5E5` pero el css asociado al control Card tiene como fondo `#E0E0E0`
En donde debería hacer el cambio para que afecte solo a las tarjetas de los eventos?

**Comment by skcode7** [comment]
Creo que ya está.
Le puse una clase `.card` en mi css de eventos.

**Comment by skcode7** [comment]
No es la solución, ya que al agregar otras clases para modificar el alto se modifica también de la parte de ciudades.

Entiendo que para evitar esto @cesardlinx comentaba que se puede utilizar ccs.modules, ya hice el cambio en el archivo de estilos y lo puedo utilizar para el estilo de la sección y el título, pero no sé como haría para modificar el estilo de la tarjeta
![imagen](https://user-images.githubusercontent.com/55223838/96354960-12bc2a80-10a2-11eb-84bb-391f9bff1a7d.png)

**Comment by skcode7** [comment]
Hasta el momento lo tengo así
![imagen](https://user-images.githubusercontent.com/55223838/96357179-e1515800-10bd-11eb-8965-3124479b1a74.png)


Necesito modificar el estilo de la tarjeta, pero no entiendo como hacerlo utilizando **css.modules**. No sé si hago el **PR** así para que alguien más pueda completar esa parte o como podría avanzar para terminarle.

**Comment by cesardlinx** [comment]
Hola @skcode7! En mi opinión está perfecto me parece genial como está quedando, lo unico que falta ahi son principalmente 3 detalles, de los cuales 2 son super fáciles de cambiar.

1. El tamaño del titulo
Esto lo puedes cambiar añadiendo una prop a la Card llamada topicFontSize

2. El color del texto "Leer más"
Esto tambien lo puedes cambiar con una prop llamada readMoreColor

Al final para resolver estos 2 issues quedaria algo asi de acuerdo al codigo que nos muestras
```JSX
<Card className={styles.card}
  imgURL={imagen}
  topic={titulo}
  date={fechaHora}  // <------Ojo los nombres de variables en javascript se deben usar camelCase
  description={resumen}
  link={url}
  topicFontSize="1rem" // <------ Esto resuelve el primer issue
  readMoreColor="#046294" // <----- Esto resuelve el segundo issue
  key={id}
/>
```
3. La altura de la imagen
Eso si implica cambiar el componente Card y agregar una prop mediante la cual se controle la altura pero que por default use la altura que tiene ahorita para no dañar la otra sección. Si te parece un poco lioso, puedes hacer el PR y luego yo en otro PR cambiaria ese detalle no habria problema por mi parte, no se que opinen tu y @israteneda.

Saludos

**Comment by israteneda** [comment]
Genial tu explicación @cesardlinx y muy detallada, como lo ves tú @skcode7 si deseas puedes completar la sección con los comentarios de @cesardlinx o a su vez puedes hacer el pull para que @cesardlinx nos ayude con esa parte o si tienes otra duda la puedes consultar aquí

**Comment by skcode7** [comment]
Estoy de acuerdo, voy a hacer los ajustes que indica @cesardlinx y realizar el **PR** para que lo puedan completar.
Gracias por la guía.

**Comment by skcode7** [comment]
Listo, acabo de hacer el **PR** con las dos correcciones indicadas por @cesardlinx 
Para el punto 3, me gustaría probar realizando el cambio en otro **issue**, que opinas @israteneda

**Comment by israteneda** [comment]
Claro no habría problema @skcode7
