### ISSUE TITLE
Crear página de Código de Conducta

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#42]
![image](https://user-images.githubusercontent.com/20668624/95895403-399bf900-0d50-11eb-95bd-798520605eb1.png)

[Aquí](https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1) se puede ver prototipo completo con más detalle.

Si tienes dudas puedes consultarlo en el canal de [Telegram de JavaScript Ecuador](https://t.me/javascriptecuador)

**Comment by jordanrjdev** [comment]
Me apunto este y si me podrian pasar el verdadero codigo seria mas genial para tenerlo listo para la produccion y que le puedan hechar un vistazo :)

**Comment by israteneda** [comment]
Claro @jordanrjcode  este es el [código de conducta](https://github.com/javascriptecuador/.github/blob/master/CODE_OF_CONDUCT.md)
