### ISSUE TITLE
Crear página de entrada del Blog

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#44]
![image](https://user-images.githubusercontent.com/11642622/94997762-d43b5180-0572-11eb-8878-0c568df95298.png)

En el siguiente link puedes el prototipo en Figma para ver los colores y tamaños de cada item

https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier inquietud puedes comentarla aquí o escribir en el [chat de la comunidad en Telegram](https://t.me/javascriptecuador)

**Comment by cesardlinx** [comment]
Me apunto para resolver este issue
