### ISSUE TITLE
Crear sección ¿Cómo Ayudar? de la página comunidad

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#45]
![image](https://user-images.githubusercontent.com/20668624/95896410-cd21f980-0d51-11eb-8d1b-07f4adccb1bb.png)

En el siguiente link puedes el prototipo en Figma para ver los colores y tamaños de cada item

https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier inquietud puedes comentarla aquí o escribir en el [chat de la comunidad en Telegram](https://t.me/javascriptecuador)

**Comment by albamaister** [comment]
Hola a todos, voy a tomar este issue si nadie mas lo a tomado. ¿Cómo le llamaría el componente de esta sección?

**Comment by israteneda** [comment]
Podría ir dentro de [community-section](https://github.com/javascriptecuador/web/tree/master/src/components/community-section) con el nombre de `hero` o `community-hero`

**Comment by israteneda** [comment]
Me equivoqué el  [community-section](https://github.com/javascriptecuador/web/tree/master/src/components/community-section) es un componente del home pensé que era una página. 
El componente se podría llamarse `community-hero-section` y podría ser similar al componente [community-section](https://github.com/javascriptecuador/web/tree/master/src/components/community-section).
