### ISSUE TITLE
Crear sección Contribuidores de la página de Comunidad

### ISSUE THREAD

**Issue by israteneda** [javascriptecuador/web#47]
![image](https://user-images.githubusercontent.com/20668624/95896657-2f7afa00-0d52-11eb-8945-1ce028b4476c.png)

Para mostrar los contribuidores en el README se está utilizando la convención [all-contrubitors](https://allcontributors.org/) es posible que se pueda reutilizar algo de la especificación en esta sección.

En el siguiente link puedes el prototipo en Figma para ver los colores y tamaños de cada item

https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier inquietud puedes comentarla aquí o escribir en el [chat de la comunidad en Telegram](https://t.me/javascriptecuador)

**Comment by cesardlinx** [comment]
Me apunto a ayudar con este feature
