### ISSUE TITLE
Crear componente subscribe

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#7]
Crear la seccion y componente subscribe en la pagina Home.

![image](https://user-images.githubusercontent.com/11642622/94997589-c76a2e00-0571-11eb-9881-dfd80d963d47.png)

En el siguiente link puedes el prototipo en figma para ver los colores y tamanios de cada item.

https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier inquietud puedes comentarla aqui o escribir en el [chat de la comuniad en telegram](https://t.me/javascriptecuador)

**Comment by jordanrjdev** [comment]
Me encargo de este issue
