### ISSUE TITLE
[Mejora] Modificar la sección de Eventos

### ISSUE THREAD

**Issue by skcode7** [javascriptecuador/web#72]
**Tarea a realizar**  
Agregar props al componente **Card** para que permita modificar el tamaño de la tarjeta y la imagen

**¿Por qué se realizará?**  
Para ajustar la sección al [diseño](https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1 "Diseño en Figma")

**Recomendaciones**  
Cambiar el componente Card y agregar una prop mediante la cual se controle la altura pero que por default use la altura que tiene ahorita para no dañar la otra sección.

**Comment by cesardlinx** [comment]
Me apunto para arreglar esa parte en la sección
