### ISSUE TITLE
[BUG] Tamaño de la última tarjeta de Ciudades

### ISSUE THREAD

**Issue by skcode7** [javascriptecuador/web#79]
**Describe el bug/error**  
Al reducir el zoom del navegar a menos del 80% la última tarjeta de ciudades no se presenta del mismo tamaño que el resto

**Para reproducirlo** 
Pasos para reproducir el comportamiento:
1. Ir a 'Home'
2. Scroll down a la sección **ciudades**
3. Reducir el zoom a menos del 80%
4. Ver el error

**Comportamiento esperado**  
Que la última tarjeta se mantenga del mismo tamaño que el resto

**Capturas de Pantalla**  
![imagen](https://user-images.githubusercontent.com/55223838/97520470-50099d80-1969-11eb-99a0-6d275ecbd1d4.png)

**Desktop:**  
 - OS: Kubuntu 20.04
 - Navegador Firefox Developer Edition
 - Versión 83

**Comment by rpalaciosg** [comment]
Gracias @skcode7 por compartir el error. Creo que es un problema puntual por que no logro reproducirlo.

![image](https://user-images.githubusercontent.com/11642622/97528907-c794f800-197c-11eb-8efb-2a72fcd81131.png)

Talvez alguna otra indice que nos puedas compartir.

**Comment by skcode7** [comment]
Te cuento que en el caso de Chrome, me ocurre cuando bajo el zoom a menos del 67%
![imagen](https://user-images.githubusercontent.com/55223838/97776580-59486500-1b37-11eb-82b9-b299f6f14bb4.png)

**Comment by thegreatyamori** [comment]
En firefox sucede lo mismo.
![image](https://user-images.githubusercontent.com/20387293/111248173-62fad280-85d7-11eb-89ba-e332e4409a83.png)
 Parece que falta de definir un max-width en la clase card-module
```css
max-width: 365px;
```
![image](https://user-images.githubusercontent.com/20387293/111248812-a43fb200-85d8-11eb-92fb-08242fe6d0b8.png)

**Comment by thegreatyamori** [comment]
@rpalaciosg yo puedo ayudar con este issue.

**Comment by rpalaciosg** [comment]
@thegreatyamori claro que si dale, nos comentas cualquier cosa.
