### ISSUE TITLE
[MEJORA] Cambiar href de Ciudades en el header

### ISSUE THREAD

**Issue by thegreatyamori** [javascriptecuador/web#88]
**Tarea a realizar**  
Se necesita que el link Ciudades en el header apunte hacia la sección 'Ciudades' de home.

**¿Por qué se realizará?**  
El motivo de realizar este cambio se debe a una reestructuración del sitio a SPA (Single Page Application).
Por esta razón la página 'Ciudades' se mantiene inactiva hasta una próxima implementación.

**Recomendaciones**  
Para desarrollar esta tarea:
- En `src\components\cities-section\cities-section.js` añadir al tag `<section>` un id.
- Ir a `src\components\header\header.js` y cambiar:
```javascript
<Link ... to="/ciudades" ... >
// --------------------------
<Link ... to="#ciudades" ... >
```

**Comment by Leninner** [comment]
Hola, trabajaré sobre este issue
