### ISSUE TITLE
Crear cuenta en bitwarden para manejo de credenciales

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#89]
Esto no forma parte del desarrollo del sitio web, pero formara parte del proyecto ya que es algo importante para la comunidad.

**Tareas a realizar**
Crear y probar cuenta gratuita en [bitwarden](https://bitwarden.com/) para el manejo y cifrado de archivos al momento de compartir credenciales.

**Objetivo**
Probar sus ventajas y en un futuro decidir si debemos pasar a un plan de pago.

**Comment by thegreatyamori** [comment]
Ayer me cambié de lastpass a bitwarden, la mejor hasta el momento. Tanto para almacenar contraseñas como para enviar archivos cifrados.

**Comment by rpalaciosg** [comment]
Hola @thegreatyamori genial saber eso, entonces vamos por buen camino, ver como nos va, y si es posible cambiarnos a un plan premiun y usar alguna app de doble autenticacion. Por el momento esta creada la cuenta, la ocmunidad y aniadidos varios logins de cuentas de la comunidad. close #89
