### ISSUE TITLE
Crear componente footer

### ISSUE THREAD

**Issue by rpalaciosg** [javascriptecuador/web#9]
Crear el footer de la pagina Home.

![image](https://user-images.githubusercontent.com/11642622/94997668-4b241a80-0572-11eb-9e9b-eea2f2e92ca1.png)

En el siguiente link puedes el prototipo en figma para ver los colores y tamanios de cada item.

https://www.figma.com/file/w2VP8mKwNivTOGqsdvGMVe/Prototipo-Web-Ecuador.js?node-id=0%3A1

Cualquier inquietud puedes comentarla aqui o escribir en el [chat de la comuniad en telegram](https://t.me/javascriptecuador)

**Comment by Seburath** [comment]
Hola! esta alguien trabajando en este Issue?

**Comment by israteneda** [comment]
No Sebas aún no he comenzado con este issue tómalo si deseas :) jajaj voy a trabajar en otro que tengo pendiente

**Comment by Seburath** [comment]
Dale, gracias!

**Comment by jordanrjcode** [comment]
Me apunto este issue

**Comment by skcode7** [comment]
No sé como avanza este tema y si pueda dar una mano.
Me falta un **PR** 🙈

**Comment by israteneda** [comment]
Si deseas puedes realizarlo, me parece que por el momento @Seburath anda atareado con el proyecto [lira](https://github.com/pythonecuador/lira). ¿Que dices @Seburath?

**Comment by Seburath** [comment]
Si! Tomalo! @skcode7 
Perdon @israteneda , me deje llevar por lo de PyEc... :(

**Comment by israteneda** [comment]
No problem @Seburath 😄 el proyecto que están lanzando está muy interesante

**Comment by skcode7** [comment]
Les comparto el resultado que tengo, seguro se puede refactorizar, pero también hice algo para la parte responsive
![imagen](https://user-images.githubusercontent.com/55223838/97776636-bfcd8300-1b37-11eb-894a-a226f3a429ef.png)

La parte de redes sociales me dio problemas (todavía me cuesta el tema de CSS) quise utilizar el componente que ya está para el **Hero** pero veo que en el **footer** deben ir más íconos. No sería mejor tener un solo componente para poder re-utilizarlo?

Puedo hacer el **PR** en el estado que está y con otro issue ajustar la parte de redes?

**Comment by israteneda** [comment]
Claro no hay problema @skcode7 sube tu **PR**. Se podría crear otro issue para la parte de las redes. Si es buena idea reutilizar el componente lo que cambiaría sería el tamaño de los iconos y el número. Pero momentáneamente si alguien lo hace en componentes separados no habría problema, crearíamos un issue para refactorizar el componente de los iconos y tenerlo en un solo componente.

**Comment by rpalaciosg** [comment]
Genial @skcode7
